export const projects = [
  {
    title: "Musée Maritime",
    images: ["./museem.webp", "./mm2.webp"],
    year: 2025,
    href: "./sample-project",
    tags: ["COMMUNICATION", "CAMPAIGN", "AD"],
  },
  {
    title: "Moonrush",
    images: ["./moonrush.webp", "./mr2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["DESIGN", "BRANDING"],
  },
  {
    title: "Suapse",
    images: ["./suapse.webp", "./suapse2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["DIGITAL", "INTERACTIVE"],
  },
  {
    title: "TMG",
    images: ["./tmg.webp", "./tmg2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["ART", "PHOTOGRAPHY"],
  },
  {
    title: "Fête de la musique",
    images: ["./fmusique.webp", "./fdlm2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["MOTION", "VIDEO"],
  },
  {
    title: "Basique",
    images: ["./basique.webp", "./basique2.webp",],
    year: 2022,
    href: "./sample-project",
    tags: ["ANIMATION", "3D"],
  },
  {
    title: "Chatelaillon",
    images: ["./chatel.webp", "./chatel2.webp",],
    year: 2024,
    href: "./sample-project",
    tags: ["CAMPAIGN", "PRINT"],
  },
  {
    title: "Book Tons",
    images: ["./tonbook.webp", "./bookt2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["WEB", "UX/UI"],
  },
  {
    title: "Marché Créatif",
    images: ["./marche.webp", "./marche2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["BRANDING", "IDENTITY"],
  },
  {
    title: "Spontex",
    images: ["./spontex.webp", "./spontex2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["DIGITAL", "AD"],
  },
  {
    title: "Francofolies",
    images: ["./franco.webp"],
    year: 2022,
    href: "./sample-project",
    tags: ["PHOTOGRAPHY", "EDITORIAL"],
  },
  {
    title: "Pixii Festival",
    images: ["./pixii.webp", "./pixii2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["FASHION", "CAMPAIGN"],
  },
  {
    title: "Lyon Biennale",
    images: ["./lyonbien.webp", "./lyonb2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["DESIGN", "PRODUCT"],
  },
  {
    title: "Neonflow",
    images: ["./neonflow.webp", "./neonflow2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["MOTION", "BRANDING"],
  },
  {
    title: "Wilee",
    images: ["./wilee.webp", "./wilee2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["ART", "INSTALLATION"],
  },
  {
    title: "Synthèse",
    images: ["./synthese.webp", "./synt2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["INTERACTIVE", "DIGITAL"],
  },
  {
    title: "Serre Rochelaise",
    images: ["./bota.webp", "./bota2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["ANIMATION", "CAMPAIGN"],
  },
  {
    title: "Rouge aux lèvres",
    images: ["./beaujolais.webp", "./beaujolais2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["VIDEO", "DOCUMENTARY"],
  },
  {
    title: "City guide",
    images: ["./maplr.webp", "./maplr2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["BRANDING", "CAMPAIGN"],
  },
  {
    title: "Almanak",
    images: ["./almanak.webp", "./almanak2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["PHOTOGRAPHY", "TRAVEL"],
  },
  {
    title: "Ideocentre",
    images: ["./ideo.webp", "./ideo2.webp"],
    year: 2022,
    href: "./sample-project",
    tags: ["3D", "DESIGN"],
  },
  {
    title: "Ricoré",
    images: ["./rico.webp", "./rico2.webp"],
    year: 2023,
    href: "./sample-project",
    tags: ["WEB", "INTERACTIVE"],
  },
  {
    title: "Graphika",
    images: ["./graphika.webp", "./graphika2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["MOTION", "AD"],
  },
  {
    title: "Redbull campaign",
    images: ["./red.webp", "./red2.webp"],
    year: 2022,
    href: "./sample-project",
    tags: ["DESIGN", "TECH"],
  },
  {
    title: "Archipel",
    images: ["./archipel.webp", "./archipel2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["CAMPAIGN", "FASHION"],
  },
    {
    title: "Théâtre de Belleville",
    images: ["./bellev.webp", "./belleville.webp"],
    year: 2024,
    href: "https://portfolio-elytra.webflow.io/theatre-belleville",
    tags: ["CAMPAIGN", "FASHION"],
  },
    {
    title: "Fête de la Saint-Jean",
    images: ["./saintjean.webp", "./saintj2.webp"],
    year: 2024,
    href: "https://portfolio-elytra.webflow.io/",
    tags: ["CAMPAIGN", "FASHION"],
  },  
  {
    title: "Tryyland",
    images: ["./tryyland.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["CAMPAIGN", "FASHION"],
  },
    {
    title: "Michel Crépeau",
    images: ["./mediatheque.webp", "./mc2.webp"],
    year: 2024,
    href: "./sample-project",
    tags: ["CAMPAIGN", "FASHION"],
  },
    {
    title: "Atelier Écriture",
    images: ["./ecriture.webp", "./ecriture2.webp"],
    year: 2024,
    href: "https://portfolio-elytra.webflow.io/atelier-ecriture",
    tags: ["CAMPAIGN", "FASHION"],
  },
];